已将主题名修改为 hexo-theme-LiuShen，以下是更新后的模板：

```yaml
name: Bug 报告
description: 创建报告以帮助我们改进
title: '[Bug]: '

body:
  - type: markdown
    attributes:
      value: |
        重要：请按照该模板提交
        Important: Please follow the template to create a new issue

  - type: input
    id: liushen-ver
    attributes:
      label: 使用的 LiuShen 版本？ | 您使用的 LiuShen 版本是什么？
      description: 查看主题的 package.json 文件 | Check the theme's package.json
    validations:
      required: true

  - type: dropdown
    id: modify
    attributes:
      label: 是否修改过主题文件？ | 主题文件是否已被修改？
      options:
        - 是 (Yes)
        - 否 (No)
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: 使用的浏览器？ | 您使用的是什么浏览器？
      options:
        - Chrome
        - Edge
        - Safari
        - Opera
        - 其他 (Other)
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 使用的系统？ | 您使用的是什么操作系统？
      options:
        - Windows
        - macOS 
        - Linux
        - Android
        - iOS
        - 其他 (Other)
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: 依赖插件 | 插件依赖信息
      description: 在 Hexo 根目录下执行 `npm ls --depth 0` | Run `npm ls --depth 0` in Hexo root directory
      render: Text
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 问题描述 | 描述该 Bug
      description: 请描述您的问题现象 | A clear and concise description of what the bug is.
      placeholder: 请尽量提供截图帮助定位问题 | If applicable, add screenshots to help explain your problem
      value:
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: 出现问题的网站 | 出现问题的网站地址
      description: 请提供可复现问题的网站地址 | Please provide a website URL where the problem can be reproduced.
      placeholder: 请填写具体的网址，不要填写 localhost | Please provide a specific URL, do not use localhost.
    validations:
      required: true
```